Update 02-variables.mkd
Line 389 what is the index entry for 'Python 2.0'?

Line 391 change input to inp in v3, to avoid conflict with function.

Line 433 update end of ValueError int() with base 10:

Line 593 - 597 Created an invalid token error, to fit example of message
>>> month = 09
     File "<stdin>", line 1
        month = 09
                        ^
SyntaxError: invalid token