Update spjson.py
Changed line 21 and 22 to reverse the order of the if conditions - when run as it was, I was getting exceptions on those lines:

Traceback (most recent call last):
  File "F:/python/Python Scripts/Coursera Code/code/code3/pagerank/spjson.py", line 21, in <module>
    if maxrank < rank or maxrank is None: maxrank = rank
TypeError: unorderable types: NoneType() < float()

Changing the test order corrected it and allowed the program to complete successfully.