The example doesn't work when only the
Code had translate modified to 1 argument from v2 (None, string.punctuation)

Test
>>> import string
>>> line = "found, return a 3-tuple containing the string itself, followed by two empty strings."

>>> string.punctuation
'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

v3.5.1
>>> line = line.translate(None, string.punctuation)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: translate() takes exactly one argument (2 given)
>>>

>>> line.translate(string.punctuation)
'found, return a 3-tuple containing the string itself, followed by two empty strings.'

the output didn't change The , - , . " were not removed, so you don't get the same answer as v2.7.11

If you run both versions of code and look at the dictionaries they are different. 

v2.7.11
>>> line.translate(None, string.punctuation)
'found return a 3tuple containing the string itself followed by two empty strings'
>>>


v3 fix
>>> line.translate(line.maketrans('','',string.punctuation))
'found return a 3tuple containing the string itself followed by two empty strings'

Another fix required in v3, use romeo.txt for less words, and sorted() to check dict, the file have UNIX EOLs and you get this

['already', 'and', 'arise', 'breaks+', 'but', 'east', 'envious', 'fair', 'grief+', 'is', 'it', 'juliet', 'kill', 'light', 'moon+', 'pal
e', 'sick', 'soft', 'sun', 'sun+', 'the', 'through', 'what', 'who', 'window', 'with', 'yonder']

the +, even though it's split()

It may be a good idea to switch to .read() and .splitlines(), but for now what's in the course, .rstrip() works.

>>> t = fh.read()
>>> t.splitlines()
['But soft what light through yonder window breaks', 'It is the east and Juliet is the sun', 'Arise fair sun and kill the envious moon'
, 'Who is already sick and pale with grief']
>>>

Also added sorted(counts) to test code for a quick visual check both v2/v3 outputs are the same. Have not written an y code to compare counts.